name: Deploy to production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest changes on the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 173.209.32.67
          port: 27
          username: gtkyll78
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/gtkyll78/public_html/wp-content
            git pull origin main
